Units change and maintaing of aspect ratio
nion-software/nionswift pull request #1079
Opened 2024-06-25 10:35 UTC by lisham2000

Added units to SVG export 
Added that it maintains aspect ratio and grays out other dimension not being specified
Solution #1051

2024-06-27 00:19 UTC, cmeyer requested changes
Thanks for the PR! I like how it works. However, I've requested several changes to make the code easier to maintain.

Also note: there is no reason to "force push" or rebase for this PR - just make new commits and regular "push" them to this PR unless you have another reason to rebase from master. That will make it somewhat easier for me to review requested changes.

2024-06-27 00:19 UTC, cmeyer commented on nion/swift/ExportDialog.py
> +                                            width=display_item.display_data_shape[0])
The dimension of `display_size` are swapped. We use the numpy convention: height is `[0]` and width is `[1]`. Try exporting a 10x100 and 100x10 data item.

2024-06-27 00:19 UTC, cmeyer commented on nion/swift/ExportDialog.py
> +            display_size = Geometry.IntSize(height=4, width=4)
For line plots (1D data), use a default size of `width=5, height=3`

2024-06-27 00:19 UTC, cmeyer commented on nion/swift/ExportDialog.py
> +
Remove this whitespace/blank line change.

2024-06-27 00:19 UTC, cmeyer commented on nion/swift/ExportDialog.py
> +    def value_updated(self, widget: Declarative.UIWidget, text: str) -> None:
Hmmm. I seem to have missed this in a bunch of other code, but let's start now!

Widgets passed to declarative callback functions are the actual widgets defined in `UserInterface.py`. So this function should be:

`def value_updated(self, widget: UserInterface.LineEditWidget, text: str) -> None:`

This goes for all similar cases in this code.

2024-06-28 12:28 UTC, lisham2000 commented
> uested several changes to make the code easier to maintain.
> 
> Also note: there is no reason to "force push" or rebase for this PR - just make new commits and regular "push" them to t

Hi Chris , the reason for the force push was having to squash since  my code seemed to pass relevant checks on my local version of Mypy when i went to push it took me multiple commits for it to pass the online one.

2024-07-17 16:15 UTC, cmeyer commented
This has been succeeded by #1100, right? Can we close this PR?

2024-07-23 21:37 UTC, lisham2000 commented
Closed due to revised version at #1106

2024-07-23 21:37 UTC, closed without merging