Add declarative color picker
nion-software/nionswift pull request #1151
Opened 2024-09-05 12:41 UTC by KRLango

This is to add a declarative version of the color picker for use in the line plot display layers section of the inspector

2024-09-05 14:25 UTC, Tiomat85 approved these changes

2024-09-09 14:01 UTC, KRLango commented
@Ion-e this PR is ready to test.

2024-10-02 09:55 UTC, Ion-e approved these changes
Draft looks good, thanks!

2024-10-02 23:19 UTC, cmeyer commented on nion/swift/Inspector.py
> +        if d_type == "color_chooser":
Like the other PR, can you make this a qualified name like "nionswift.color_chooser" to make it easier to migrate this code to `nionui` in the future? Thanks!

2024-10-02 23:20 UTC, cmeyer requested changes
Like the other PR, can you make this a qualified name like "nionswift.color_chooser" to make it easier to migrate this code to `nionui` in the future? Thanks!

2024-10-03 11:56 UTC, Tiomat85 approved these changes

2024-10-04 00:46 UTC, cmeyer commented
Merged 4d1937b3c9c221f13c656215334e70c095daf163

2024-10-04 00:46 UTC, closed without merging