Ensure graphic and calculated mask match
nion-software/nionswift pull request #1254
Opened 2024-11-19 15:58 UTC by KRLango

#1140 
After trying the approach I suggested, I saw the problems that @cmeyer referenced with it so ended up implementing his original solution as I believe that it is a better user experience.

2025-01-08 09:18 UTC, Tiomat85 approved these changes

2025-01-08 19:33 UTC, Ion-e reviewed
Looks good!

2025-01-27 16:58 UTC, jamesrussell216 commented
Can this one be put in now @KRLango?

2025-01-27 19:36 UTC, cmeyer commented
This still looks incorrect... in the first screenshot below, the mode is set to 'low pass' and the resulting masked image (lower left) is showing (i.e. "passing") the high frequency data (further from FFT center). In the second screenshot below, the opposite is occuring - the low frequency (closer to FFT center) is being "passed". I don't know how you want to fix it, but I think the 'low pass' and 'high pass' labels in the inspector are still reversed - but I think instead of changing the inspector, 'get_mask' and 'draw' (band pass) should be reversed. This might introduce backwards incompatibility in the file format, but I think it's acceptable to get it right.

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/f6ee9379-5b5e-46eb-a2fb-1cbf0f90dda6" />

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/91739344-23f4-4522-9e9a-6e5a9b92df1f" />

2025-01-27 19:36 UTC, cmeyer requested changes
See comment above.

2025-01-29 14:31 UTC, jamesrussell216 commented
@cmeyer just looking at your screenshots there - is it my imagination or is there a weird ~few pixel shift of the top hemisphere to the bottom in the masked images?

2025-01-29 16:07 UTC, cmeyer commented
Yes that needs to be investigate, although this could be a consequence of the Hermitian data layout.

2025-03-27 14:39 UTC, KRLango commented
It has been a while since I last looked at this and the code has progressed to the point where it is easier to make a new branch and PR rather than try and merge this one. Specifically some of the functions this PR edits have moved into new classes. The new PR is #1396

2025-03-27 14:39 UTC, closed without merging